### ISSUE TITLE
The Decoder does not support the image format `A decoder for PNG is not available.`

### ISSUE THREAD

**Issue by woelper** [PistonDevelopers/texture_packer#58]
when running `cargo run --example packer-test` in the root directory the example panics with 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "The Decoder does not support the image format `A decoder for PNG is not available.`"'
```
This is on windows 10 with rustc 1.33.0-nightly. I can read and write pngs with the image crate in other projects fine.

**Comment by woelper** [comment]
i just changed the cargo.toml to just have these dependencies and it works:
```
[dependencies]
image = { version = "0.21.0", default-features = true }
```

**Comment by MichaelMcDonnell** [comment]
It is possible to run the example by passing the features flag:

```console
$ cargo run --features="png_codec" --example packer-test
```

Updating the README with that is probably the simplest option.

Another option is to only enable `png_codec` instead of all the default features:

```toml
[dependencies.image]
version = "0.22.1"
default-features = false
features = ["png_codec"]
```

I also tried setting the `required-features` key but that did not work:

```toml
[[example]]
name = "packer-test"
required-features = ["png_codec"]
```

I think the `required-features` doesn't work because of rust-lang/cargo/issues/4663
